site_name: LiveSYNC™ Learning Center
nav:
  - Home: 'README.md'
  - How to use this site: 'site_howto/site_howto.md'
  - Quick Start:
    - Index: 'quick_start/quick_start.md'
    - Presentation:
      - Devices: 'quick_start/presentation_devices.md'
      - Software: 'quick_start/presentation_software.md'
      - Configuration: 'quick_start/presentation_configuration.md'
      - Files: 'quick_start/presentation_files.md'
      - Channel: 'quick_start/presentation_channel.md'
      - Joining: 'quick_start/presentation_joining.md'
      - Presenting: 'quick_start/presentation_presenting.md'
      - Mirroring: 'quick_start/presentation_mirroring.md'
  - Tutorials:
    - Index: 'tutorials/tutorials.md'
    - LiveSYNC on Oculus Go:
      - Device: 'tutorials/oculus_go_device.md'
      - Setup: 'tutorials/oculus_go_setup.md'
      - Preparing: 'tutorials/oculus_go_preparing.md'
      - Presenting: 'tutorials/oculus_go_presenting.md'
      - Tips: 'tutorials/oculus_go_tips.md'
  - User Guide:
    - Index: 'user_guide/user_guide.md'
    - 1. Introduction: 'user_guide/introduction.md'
    - 2. Installing: 'user_guide/installing.md'
    - 3. Configuration: 'user_guide/configuration.md'
    - 4. Managing assets: 'user_guide/asset_management.md'
    - 5. Workspace: 'user_guide/workspace.md'
    - 6. Presenting: 'user_guide/presenting.md'
    - 7. Photo content: 'user_guide/photo_content.md'
    - 8. Video content: 'user_guide/video_content.md'
    - 9. Tags & hotspots: 'user_guide/hotspots.md'
    - 10. Workflows: 'user_guide/workflows.md'
    - 11. Editor: 'user_guide/editor.md'
    - 12. Troubleshooting: 'user_guide/troubleshooting.md'
  - Articles:
    - Index: 'articles/articles.md'
    - Understanding resolution: 'articles/resolution.md'
  - FAQ:
    - Index: 'faq/faq.md'
  - Support:
    - Index: 'support/support.md'
  - Downloads:
    - Index: 'downloads/downloads.md'
theme:
  name: 'material'
  feature:
    tabs: true
markdown_extensions:
  - admonition
