site_name: LiveSYNC™ Learning Center
nav:
  - Home: 'README.md'
  - Quick Start: 'quick_start.md'
  - Tutorials: 'tutorials.md'
  - User Guide: 'user_guide.md'
  - Articles: 'articles.md'
  - FAQ: 'faq.md'
  - Support: 'support.md'
  - Downloads: 'downloads.md'
theme:
  name: 'material'
#  name: 'bootstrap4'
#  name: 'gitbook'
