site_name: LiveSYNC™ Learning Center
nav:
  - Home: 'README.md'
  - Quick Start: 'quick_start/quick_start.md'
  - Tutorials: 'tutorials/tutorials.md'
  - User Guide: 'user_guide/user_guide.md'
  - Articles: 'articles/articles.md'
  - FAQ: 'faq/faq.md'
  - Support: 'support/support.md'
  - Downloads: 'downloads/downloads.md'
theme:
  name: 'material'
